esphome:
  name: roomba
  platform: ESP8266
  board: d1_mini
  includes:
    - roomba_component.h
  libraries:
    - Roomba=https://github.com/Apocrathia/Roomba

substitutions:
  name: "roomba"
  # BRC pin, polling interval in milliseconds
  init: 'RoombaComponent::instance(D5, 1000);'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

ota:

custom_component:
  - lambda: |-
      auto r = ${init}
      return {r};
sensor:
 - platform: custom
   lambda: |-
      auto r = ${init}
      return {r->distanceSensor, r->voltageSensor, r->currentSensor, r->chargeSensor, r->capacitySensor, r->batteryPercentSensor};

   sensors:
     - name: "${name} distance"
       unit_of_measurement: "mm"
       accuracy_decimals: 0
     - name: "${name} voltage"
       unit_of_measurement: "mV"
       accuracy_decimals: 0
     - name: "${name} current"
       unit_of_measurement: "mA"
       accuracy_decimals: 0
     - name: "${name} charge"
       unit_of_measurement: "mAh"
       accuracy_decimals: 0
     - name: "${name} capacity"
       unit_of_measurement: "mAh"
       accuracy_decimals: 0
     - name: "${name} battery"
       unit_of_measurement: "%"
       accuracy_decimals: 0
       
text_sensor:
  - platform: custom
    lambda: |-
      auto r = ${init}
      return {r->activitySensor};
      
    text_sensors:
      - name: "${name} activity"

# remote_transmitter:
#   pin: D2
#   carrier_duty_percent: 50%
  
# switch:
#   - platform: template
#     id: "roomba_clean"
#     name: "Roomba Clean"
#     icon: "mdi:robot-vacuum"
#     turn_on_action:
#       - remote_transmitter.transmit_raw:
#           repeat: 30
#           carrier_frequency: 39kHz
#           code: [2872,-999,897,-2872,897,-2872,897,-2872,2872,-999,897,-2872,897,-2872,897] 
