esphome:
  name: roomba
  friendly_name: Roomba

esp8266:
  board: nodemcuv2

external_components:
  - source:
      type: git
      url: https://github.com/wburgers/ESPHomeRoombaComponent

uart:
  id: uart_bus
  tx_pin: D1
  rx_pin: D2
  baud_rate: 115200
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

# Enable logging
logger:
  hardware_uart: UART1

# Enable Home Assistant API
api:
  custom_services: true
  encryption:
    key: "<your key here>"

ota:
  - platform: esphome
    password: !secret OTA_password

wifi:
  networks:
  - ssid: !secret wifi_ssid_new
    password: !secret wifi_password_new
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  min_auth_mode: WPA2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Roomba Fallback Hotspot"
    password: !secret Fallback_portal_password

captive_portal:

status_led:
  pin:
    number: GPIO2
    inverted: True

roomba_component:
  id: roomba
  update_interval: 30s

sensor:
  - platform: roomba_component
    battery_level:
      name: "Roomba Battery"
    battery_capacity:
      name: "Roomba Battery Capacity"
    voltage:
      name: "Roomba Voltage"
    temperature:
      name: "Roomba Battery Temperature"
    charging_state:
      name: "Roomba Charging State"

text_sensor:
  - platform: roomba_component
    activity:
      name: "Roomba Activity Status"