esphome:
  name: roomba
  platform: ESP8266
  board: d1_mini
  includes:
    - ESPHomeRoombaComponent.h

substitutions:
  name: "roomba"
  # BRC pin, uart_bus, polling interval in milliseconds, enable hack for lazy 650 wakeup
  init: 'RoombaComponent::instance(D5, id(uart_bus), 10000, true);'

uart:
  id: uart_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 115200

# Enable logging
logger:
  hardware_uart: UART1

# Enable Home Assistant API
api:
  password: !secret API_password

ota:
  password: !secret OTA_password

wifi:
  ssid: !secret WiFi_ssid
  password: !secret WiFi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Roomba Fallback Hotspot"
    password: !secret Fallback_portal_password

captive_portal:

status_led:
  pin:
    number: GPIO2
    inverted: True

custom_component:
  - lambda: |-
      auto r = ${init}
      return {r};

sensor:
 - platform: custom
   lambda: |-
      auto r = ${init}
      return {r->voltageSensor, r->currentSensor, r->batteryChargeSensor, r->batteryCapacitySensor, r->batteryPercentSensor, r->batteryTemperatureSensor, r->driveSpeedSensor};
   sensors:
  - name: "${friendly_name} voltage"
    unit_of_measurement: "V"
    icon: mdi:sine-wave
    accuracy_decimals: 2
    filters:
    - quantile:
        window_size: 7
        send_every: 4
        send_first_at: 3
        quantile: .9
    - multiply: 0.001
  - name: "${friendly_name} current"
    unit_of_measurement: "A"
    icon: mdi:lightning-bolt
    accuracy_decimals: 3
    filters:
    - quantile:
        window_size: 7
        send_every: 4
        send_first_at: 3
        quantile: .9
    - multiply: 0.001
  - name: "${friendly_name} charge"
    unit_of_measurement: "Ah"
    icon: mdi:battery-charging
    accuracy_decimals: 2
    filters:
    - quantile:
        window_size: 7
        send_every: 4
        send_first_at: 3
        quantile: .9
    - multiply: 0.001
  - name: "${friendly_name} capacity"
    unit_of_measurement: "Ah"
    icon: mdi:battery
    accuracy_decimals: 2
    filters:
    - quantile:
        window_size: 7
        send_every: 4
        send_first_at: 3
        quantile: .9
    - multiply: 0.001
  - name: "${friendly_name} battery"
    unit_of_measurement: "%"
    state_class: "measurement"
    device_class: battery
    icon: mdi:battery-outline
    accuracy_decimals: 0
    filters:
    - quantile:
        window_size: 7
        send_every: 4
        send_first_at: 3
        quantile: .9
  - name: "${friendly_name} temperature"
    unit_of_measurement: "°C"
    icon: mdi:thermometer
    accuracy_decimals: 0
    filters:
    - quantile:
        window_size: 7
        send_every: 4
        send_first_at: 3
        quantile: .9
  - name: "${name} drive speed"
    unit_of_measurement: "mm/s"
    accuracy_decimals: 0


text_sensor:
  - platform: custom
    lambda: |-
      auto r = ${init}
      return {r->chargingSensor, r->activitySensor, r->oiModeSensor};
    text_sensors:
      - name: "${name} charging state"
      - name: "${name} activity"
      - name: "${name} OI mode"

switch:
  - platform: safe_mode
    name: "Vacuum Restart (Safe Mode)"
